### PR TITLE
Proposal for eager loading

### PR DESCRIPTION
**Pull request by nicolas-chaulet**
Proposal to address #2

### CODE REVIEW

**Comment by Kludex** [comment]
I think it makes sense to have what you propose, but I'm not sure if I like the API.

What do you think about this:

```python
@pytest.mark.asyncio
async def test_eagerload(session: AsyncSession) -> None:
    collection = await Potatoes.create(session)
    await Potato.create(session, name="Blue", potato_collection_id=collection.id)
    await Potato.create(session, name="Red", potato_collection_id=collection.id)

    potatoes = await load_strategy(Potatoes.get, potatoes="selectin")(session) # here
    assert len(potatoes.potatoes) == 2
```

Alternative usage:
```python
    get_potatoes = load_strategy(Potatoes.get, potatoes="selectin")
    potatoes = await get_potatoes(session)
```

Different API:
```python
    get_potatoes = load_strategy(Potatoes.get, options={"potatoes": "selectin"}) # use `options` instead of `kwargs`
    potatoes = await get_potatoes(session)
```

Are there more "modifiers" that we can use?

Thoughts about this?

**Comment by nicolas-chaulet** [comment]
I think the `get_potatoes = load_strategy(Potatoes.get, potatoes="selectin")` would be the one I prefer, I am not a fan of dictionaries, too many strings 😄

**Comment by Kludex** [comment]
What about:

```python
with load_strategy(potatoes="selectin"):
    potatoes = await Potatoes.get(session)
```
:thinking:

**Comment by nicolas-chaulet** [comment]
Yes I like that one but I'm wondering if it is not as simple to write the raw select statement at that point now that we go through it. Bottom line is, which syntax is simpler to remember?

**Comment by Kludex** [comment]
I've thought about this... You're right.

Looks simpler.

**Pull request closed without merging**
